include:
  - path: deps.docker-compose.yaml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: 1000:1000
    ports:
      - 4000:4000 # hono
      - 4983:4983 # drizzle-studio
    entrypoint: ['/app/entrypoint.dev.sh']
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: pguser
      PG_PASSWORD: pgpassword
      PG_DB: pechomax_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
