services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    networks:
      - dokploy-network
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      COOKIE_SECRET: ${COOKIE_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      PAGE_SIZE: ${PAGE_SIZE}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV}

networks:
  dokploy-network:
    external: true
